### ISSUE TITLE
Manage Users - Re-auth example

### ISSUE THREAD

**Issue by tRackRR** [JohnCoene/firebase#10]
Hey there, 

First, thanks for the package! 

I maybe just found a little issue with one of the examples you had here (https://firebase.john-coene.com/articles/manage.html) on your Manage Users page:

`f <- FirebaseEmailPassword$new()
observeEvent(input$reAuth, {
  f$re_authenticate(input$reAuthPassword)
})

observeEvent(input$get_re_authenticated(), {
  reauth <- input$get_re_authenticated()
  print(reauth$success)
})`

Shouldn't input$get_re_authenticated() be replaced by f$get_re_authenticated()?

Thanks!

**Comment by JohnCoene** [comment]
Yes, thank you for reporting this!
