### ISSUE TITLE
persistence error

### ISSUE THREAD

**Issue by dcaud** [JohnCoene/firebase#14]
I made a bunch of changes to an app and an error popped up in Chrome console -- something about persistent state...

The error went away when I changed this:

`f <- FirebaseUI$new(persistence = "local")$set_providers()`

to 

`f <- FirebaseUI$new()$set_providers()`

My old version worked with persistence = "local" and that's the way I'd prefer things to work. 

The one other major change is that I had an app within an app (double iframes), so the problem may have had something to do with that.

Can you confirm that persistence = "local" is working as expected? Sorry, I've no time to create a MWE of my problem.

Thanks

**Comment by JohnCoene** [comment]
Indeed, changes on v8.1 on how this is handled, persistence was not properly registered: pushed a fix. Reinstall from github.
