### ISSUE TITLE
Error in private$.namespace

### ISSUE THREAD

**Issue by richardsprague** [JohnCoene/firebase#17]
I'm completely unable to get any of the documentation examples to work. Shiny loads and appears to think I'm already logged in; even on first launch the only UI I see is the "Sign out" action button.  I've tried on different machines, new Google firebase account, config file vs environ vars,  but absolutely nothing works.  Same results whether I use CRAN version or ‘1.0.0.9000’

One clue. I wonder why do I get this message
```r
> f <- FirebaseUI
> f$new()$set_providers(email=TRUE, google=TRUE)
ℹ Fetching firebase config from environment variables
Error in private$.namespace(session) : attempt to apply non-function
```

**Comment by JohnCoene** [comment]
I'm sorry.

There was indeed an issue with the package which I just fixed. However, it was with JavaScript and not the R6 class.

Could you reinstall from Github and retry.

If it works, close this issue, if it does not, tell me which browser you are using.

**Comment by richardsprague** [comment]
It works now!  Thanks for the quick response.
