### ISSUE TITLE
RMarkdown

### ISSUE THREAD

**Issue by deepanshu88** [JohnCoene/firebase#2]
Does it work in Rmarkdown? I am using shiny_prerendered markdown doc. I am including all JS and CSS of firebase package using **tags$head( )**

The code below does not work in any of this including or excluding **context='server'**- 
```
  f <- FirebaseUI$
    new()$ # instantiate
    set_providers( # define providers
      email = TRUE, 
      google = TRUE
    )
```

**Comment by JohnCoene** [comment]
Sorry this issue went by and I forgot about it, apologies.

This is not possible as it requires the shiny back-end (server) to work.
