### ISSUE TITLE
Blank page for example

### ISSUE THREAD

**Issue by dcaud** [JohnCoene/firebase#21]
The example below returns a blank white page in Chrome.

I see this error in the Chrome console:

> Failed to load resource: the server responded with a status of 404 (Not Found)

```
library(shiny)
library(firebase)

ui <- fluidPage(
  useFirebase(), # import dependencies,
  firebaseUIContainer()
)

server <- function(input, output){
  f <- FirebaseUI$
    new()$ # instantiate
    set_providers( # define providers
      email = TRUE, 
      google = TRUE
    )$
    launch() # launch
}

shinyApp(ui, server)
```

**Comment by dcaud** [comment]
Here's my session info:

> sessionInfo()
> R version 4.1.1 (2021-08-10)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Monterey 12.1
> 
> Matrix products: default
> LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] tools     stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] shinyBS_0.61       jsonlite_1.7.2     mongolite_2.4.1    future.callr_0.7.0
>  [5] ipc_0.1.3          httr_1.4.2         purrr_0.3.4        future.apply_1.8.1
>  [9] future_1.23.0      promises_1.2.0.1   googleAuthR_1.4.1  firebase_1.0.0    
> [13] RPostgres_1.4.3    pool_0.1.6         dplyr_1.0.7        shinyjs_2.1.0     
> [17] pdftools_3.0.1     shinybusy_0.2.2    shinyWidgets_0.6.2 magick_2.7.3      
> [21] colourpicker_1.1.1 shiny_1.7.1       
> 
> loaded via a namespace (and not attached):
>  [1] sass_0.4.0        bit64_4.0.5       bslib_0.3.1       assertthat_0.2.1 
>  [5] askpass_1.1       base64url_1.4     blob_1.2.2        globals_0.14.0   
>  [9] qpdf_1.1          pillar_1.6.4      backports_1.4.1   glue_1.6.0       
> [13] digest_0.6.29     colorspace_2.0-2  htmltools_0.5.2   httpuv_1.6.5     
> [17] pkgconfig_2.0.3   listenv_0.8.0     xtable_1.8-4      scales_1.1.1     
> [21] fontawesome_0.2.2 processx_3.5.2    later_1.3.0       tibble_3.1.6     
> [25] openssl_1.4.6     txtq_0.2.4        generics_0.1.1    ggplot2_3.3.5    
> [29] ellipsis_0.3.2    cachem_1.0.6      withr_2.4.3       cli_3.1.0        
> [33] magrittr_2.0.1    crayon_1.4.2      mime_0.12         memoise_2.0.1    
> [37] ps_1.6.0          fs_1.5.2          fansi_0.5.0       parallelly_1.30.0
> [41] hms_1.1.1         gargle_1.2.0      lifecycle_1.0.1   munsell_0.5.0    
> [45] callr_3.7.0       compiler_4.1.1    jquerylib_0.1.4   rlang_0.4.12     
> [49] grid_4.1.1        rstudioapi_0.13   htmlwidgets_1.5.4 miniUI_0.1.1.1   
> [53] base64enc_0.1-3   gtable_0.3.0      codetools_0.2-18  curl_4.3.2       
> [57] DBI_1.1.2         R6_2.5.1          lubridate_1.8.0   fastmap_1.1.0    
> [61] bit_4.0.4         utf8_1.2.2        filelock_1.0.2    parallel_4.1.1   
> [65] Rcpp_1.0.7        vctrs_0.3.8       jose_1.2.0        tidyselect_1.1.1

**Comment by JohnCoene** [comment]
Sorry, I must have messed up my recent CRAN submission: I pushed a fix to Github

**Comment by dcaud** [comment]
Running `remotes::install_github("JohnCoene/firebase")` and starting a new R session got me an expected login page. I think that works (until CRAN updates, which I'll ultimately want to use).

**Comment by JohnCoene** [comment]
Yes, it's my bad; I should have been more careful. Sorry.

I can push to CRAN next month

**Comment by dcaud** [comment]
No apologies necessary. Thanks again for your package and fast responses about issues!
