### ISSUE TITLE
Empty providerData

### ISSUE THREAD

**Issue by gregleleu** [JohnCoene/firebase#23]
Hi,
I'm getting an empty list in `f$get_signed_in()$response$providerData` where previously I would get microsoft.com or other providers being used.
But confusingly when I reload the page ("session" persistence) the providerData field is filled.
I haven't been able to figure out why this is happening :(

(I'm using this to check which provider is being used, if it is email then I check whether the email has been verified).

thanks!

**Comment by gregleleu** [comment]
Apparently an issue with the underlying libraries 

https://stackoverflow.com/questions/69958514/firebase-authentication-js-does-not-populate-providerdataarray

**Comment by gregleleu** [comment]
After a lof of research, it's actually a bug in firebase.js reported here https://github.com/firebase/firebaseui-web/issues/917 and fixed with version 9.6.6 https://firebase.google.com/support/release-notes/js#version_966_-_february_3_2022 
I've updated to the latest firebase (9.6.7) and firebaseui (1.0.1) in my fork and it seems to be working just fine. Do you think you could update here?

Side note: I've tried the user.relaod() workaround mentioned in my previous post's link. It works but for some unknown reason flashs a "setInputValue not defined" error through firebaseui just before the UI container gets hidden.

**Comment by JohnCoene** [comment]
Ok, thanks for looking into this.

I just updated firebase to `9.6.7` (latest) and rebuilt. Can you install the latest dev and let me know if that works?

**Comment by gregleleu** [comment]
Seems to be working so far, thanks!

(email+password isn't working – no emails are being sent – but I guess it has nothing to do with this)

**Comment by JohnCoene** [comment]
Emails + password does not send emails.

**Comment by gregleleu** [comment]
Didn't it use to do it? I tried "f$get_verification_email()" also but to no avail. I fell back to email link
Probably not the right place for this discussion ;)
