### ISSUE TITLE
Microsoft Docs client secret

### ISSUE THREAD

**Issue by munoztd0** [JohnCoene/firebase#32]
hello,

Just FYI, I succeed in using microsoft AAD with your package (thanks btw for the amazing work !)  ,

BUT I spend 3 hours to figure out that what I needed was the "Value" and not the "Secret ID" for the client secret that needs to be inputed to firebase.

![image](https://user-images.githubusercontent.com/43644805/167895737-55e67613-36cc-47c1-8934-12978260d0bd.png)

So I just let it here in case people run into the same thing or maybe if you want to update the https://firebase.john-coene.com/auth/oauth-providers/ for new arrivers.

Anyway thanks again!

**Comment by JohnCoene** [comment]
Ah, could you telling more precisely which step/bullet I should add and where?

**Comment by munoztd0** [comment]
Yes of course !  Here I bolded some stuff that I added that took me time to figure out,


 Microsoft

Authenticating via Microsoft is handled by Microsoft Azure, create a free account if you do not have one the:

Visit the portal
Search and select “Azure Active Directory”
In the left sidebar under “Manage” select “App registrations”
Then click New registrations
**Under API permissions give "User.Read" permissions to Microsoft Graph API.**
Under “Redirect URI” select “Web” and place the redirect URL given by Firebase
Once created, on the “overview” screen copy the “Application (client) ID” to Firebase **(find it within the firebase console under microsoft Sign-in method )**
Then visit “Certificates & secrets” in the sidebar
Create a “New client secret” and copy it **(watch out you need to copy the "Value" not the "Secret ID" field) to Firebase (within the firebase console microsoft Sign-in method under "Application secret")**
Once this done give Microsoft 2 minutes to sync before trying the authentication.

**Comment by munoztd0** [comment]
PS1: I really can figure out how to get group membership info from the response output, do you have any idea where I could start to look ?

PS2: Pierre Saouter says hello!

**Comment by JohnCoene** [comment]
Thanks I updated the docs.

For your questions on groups, I'm afraid I do not know, what you get from the response is everything Firebase returns, hopefully it's in there somewhere.

**Comment by munoztd0** [comment]
Cool thanks but I found a work around instead of going trough the API.
