### ISSUE TITLE
Microsoft accessToken returned after sign-in returns 401 error when used for Microsoft Graph API

### ISSUE THREAD

**Issue by BilboBaagins** [JohnCoene/firebase#54]
Hey John, 

According to the [firebase docs](https://firebase.google.com/docs/auth/web/microsoft-oauth#web-version-8:~:text=On%20successful%20completion,com/v1.0/me), you should be able to query Microsoft's Graph API with the access token retrieved after sign-in. 

However, when I try to query Microsoft's Graph API with the accessToken that is returned with `get_signed_in()$response$stsTokenManager$accessToken`, I get a `401 error` with the following message informing me that the `Required claim nbf not present in token`.

I have tried a couple of different approaches such as manually adding the nbf claim, however this is still unsuccessful. 

I have also successfully retrieved the accessToken using the `AzureAuth` package `AzureAuth::get_azure_token()` outside of my Shiny web app environment.  I can successfully query the Graph API with this token.  When I compare both tokens using https://jwt.ms/, I see this token has the `nbf` claim and a bunch of other additional claims.

Because I can successfully retrieve the token using `AzureAuth::get_azure_token()`, I am confident that my app registration is set up correctly and the issue may be caused on the firebase side.  

I also note another firebase user posted a [similar issue on StackOverflow](https://stackoverflow.com/questions/72394513/required-claim-nbf-not-present-in-token-using-firebase-microsoft-signin-trying), where they were attempting to use the accessToken they retrieved from signing in via the `signInWithPopup` method of authentication and also getting a `401` from the Graph API.  Therefore, I'm not sure if the issue lies with the firebase package itself rather than your R package, or if it is something I am doing incorrectly. 

Thanks again for a great package!

**Comment by JohnCoene** [comment]
I think this may be the issue.

```js
// Get the OAuth access token and ID Token
const credential = OAuthProvider.credentialFromResult(result);
const accessToken = credential.accessToken;
const idToken = credential.idToken;
```

I don't do the above because as indicated `// User is signed in` already at that stage.
I don't think you have the correct token there.

**Comment by JohnCoene** [comment]
Pushed something, let me know if it works

```r
library(shiny)
library(firebase)

ui <- fluidPage(
  useFirebase(), 
  firebaseUIContainer()
)

server <- function(input, output){
  f <- FirebaseOauthProviders$
    new()$ 
    set_provider("microsoft.com")$
    launch(flow="popup", get_credentials = TRUE) # capture credentials
}

shinyApp(ui, server)
```

Then look at `get_signed_in()$response$credentials`

**Comment by BilboBaagins** [comment]
Brilliant, thanks for looking at it. 

Nothing working yet,  `f$get_signed_in()$response$credentials` returns `null`.

**Comment by BilboBaagins** [comment]
Super, thanks for the information John. 

`get_signed_in()$response$credentials` is still returning `null`.  It looks like `results` is still referenced in `inst/packer/oauth.js` instead of `result` or `s`.

**Comment by JohnCoene** [comment]
No that's been updated, problem must be elsewhere

**Comment by BilboBaagins** [comment]
Haha, stop it's easy done when you're spinning plates!

Unfortunately `get_signed_in()$response$credentials` is still returning `null`.

**Comment by JohnCoene** [comment]
That's a big change that'd require quite a bit of testing.

There is technically a difference between sign in and sign up.

Also the response from a sign in is post processed here, so we need to be sure that sign up == sign in before we go ahead with this.
https://github.com/JohnCoene/firebase/blob/072fd5d8c7c25f52a3bec92c8d160edb164e1698/R/class-auth.R#L220

This is to ensure the login is valid.

Could you try to listen to that input directly? 
Should be 

```r
# add namespace optionally
observeEvent(input$fireblaze_signed_up_user, {...})
```

**Comment by JohnCoene** [comment]
Thanks for your patience, and if you want to help me maintain this PRs are more than welcome.

There are probably issues in the logic, e.g.: the multiple trigger of inputs (getting `NULL`s)

**Comment by BilboBaagins** [comment]
Thank you for your speedy responses.  Absolutely, I'd love to help out.  I'm going to try and get up to speed with packer so I can trial and error on my fork.

**Comment by JohnCoene** [comment]
Clone and install the js dependencies with `packer::npm_install()`

Then:

1. Edit javascript
2. `packer::bundle()`

**Comment by BilboBaagins** [comment]
I just realised that I changed `signed_up_user` to `signed_in_user` on my local `packer\oauth.js` file earlier as a stab in the dark and never reverted my changes...

You were spot on suggesting `observeEvent(input$fireblaze_signed_up_user, {...})`.

`input$fireblaze_signed_up_user$response$credentials$accessToken` returns the desired `oauthAccessToken`.

It's not returning multiple `NULL`s either thankfully - my bad!

> So listening to `input$fireblaze_signed_up_user` does nothing but listening to `input$fireblaze_signed_in_user` returns a whole bunch of inputs, including the oauthAccessToken.
