### ISSUE TITLE
Something is wrong, but I don't know what

### ISSUE THREAD

**Issue by dcaud** [JohnCoene/firebase#55]
Just a heads up that it looks like firebase is currently acting differently than it was a few hours ago. I'm digging to figure out what is going on, but so far my guess is that the values or type of values returned from `f$get_signed_in()$response` are now different.

The problem does not appear when running a shiny app locally, but rather just on shinyapps.io. 

I'll post more when I know more!

**Comment by JohnCoene** [comment]
Do you know which version you were running?

**Comment by dcaud** [comment]
firebase_1.0.1

**Comment by JohnCoene** [comment]
The latest commit changes very little, no `if` statement.

https://github.com/JohnCoene/firebase/commit/0d497175631ef404c235d77888e2437502ec3ef8

It must be from the previous commit (10 months old) which is a security fix by verifying tokens server-side.

If it fails it's not a good sign.

No one reported issue thus far though.

Which Auth method are you using?

Config or environment variables?

**Comment by dcaud** [comment]
The latest commit is not the problem. It may be a problem with other code and not firebase (sorry if that's the case!).

I am using google, email, and twitter auth methods.
I *think* I'm using environment variables.

The problem may very well be with shinyapps.io... locally I'm not seeing the problem, which makes it very difficult to debug.

**Comment by dcaud** [comment]
So, I'm still not totally sure what is happening, but I have a few facts:

Things work as expected if:
1. I use Chrome incognito
2. I use Safari (both regular and private browsing)

Things don't work if:

1. I use regular Chrome.

I'm still not sure if this has anything to do with Firebase, but thought I would post here in case others have a similar issue.

**Comment by dcaud** [comment]
So, I cleared browser cache and got it working again. It might have been that a firebase local cache wasn't cleared from an old account and my app didn't handle that well. Closing for now. Sorry for the trouble!
