### ISSUE TITLE
Access via JS

### ISSUE THREAD

**Issue by johnbde** [JohnCoene/firebase#7]
Thanks for this great package. I am trying to access it via JS as I am using it in Rmarkdown. The code below works ( it hides elements when user is logged out). But it does not work when I want to show elements after user is logged in. To show I am using `fireblaze__requires__signin` and `.show( )`

```

**Comment by JohnCoene** [comment]
Did you find a way to make this work?

**Comment by johnbde** [comment]
I tried via `$('#fireblaze-signin-ui').is(':visible')` and `$('#fireblaze-signin-ui').is(':hidden')`. It works but I realized today when I logged off after log in once, it stops working. It still hides elements.  

// Hide when user is NOT logged in:
$(document).ready(function() {
var CONTROL_INTERVAL3 = setInterval(function(){
if($('#fireblaze-signin-ui').is(':visible')){

  clearInterval(CONTROL_INTERVAL3);
} }, 200);
});
    
// Show when user is logged in:
$(document).ready(function() {
var CONTROL_INTERVAL4 = setInterval(function(){
if($('#fireblaze-signin-ui').is(':hidden')){

  clearInterval(CONTROL_INTERVAL4);
} }, 200);
});
