### ISSUE TITLE
UI allows registration, but not sign in

### ISSUE THREAD

**Issue by simitpatel** [JohnCoene/firebase#71]
Hello,

Thank you for this package (and all the others!), and apologies if this is not the correct venue for this. I have followed the demo application provided in the documentation and a few variations of it, but I continue to experience the same problem:

1. The shiny app launches with the basic UI
2. There is only the option to register a new user -- not for an already registered user to login
3. New users who register experience the app as intended. Pre-existing users who attempt to register again with the same email are greeted with this message:

```This email already exists without any means of sign-in. ```

Any idea what is going on here? Below is the code I'm using. You can also experience it in [the shiny app on shinyapps.io](https://sixjupiter.shinyapps.io/longformer/). firebase 1.0.2 (tried with 1.0.0 also), R 4.2.0, shiny 1.7.5 and 1.7.3. 

```library(shiny)
library(firebase)

ui <- fluidPage(
  useFirebase(),
  firebaseUIContainer(),
  reqSignin(actionButton("signout", "Sign out")),
  uiOutput("msg"),
  plotOutput("plot")
)

server <- function(input, output){
  f <- FirebaseUI$
    new()$ # instantiate
    set_providers( # define providers
      email = TRUE,
      google = TRUE
    )

  observe({
    launch() # launch
  })
}

shinyApp(ui, server)
``` 

any help is greatly appreciated!

**Comment by JohnCoene** [comment]
Apologies, I only just saw that.

With the firebase UI there is no distinction between a registration and a login.

It makes sense to me, it's practically the same thing.

I've never seen this error message where does it occur, could you share the full error?
