### ISSUE TITLE
firebaseUIContainer() does not show up in modal after sign out

### ISSUE THREAD

**Issue by durraniu** [JohnCoene/firebase#75]
This is based on the example in the documentation: https://firebase.john-coene.com/auth/social/

## Goal
Display login buttons in a modal

## Issue
The login buttons show up in a modal when signing in the first time. But when you sign out, the modal shows up without the `firebaseUIContainer()`. However, after a refresh, the login buttons appear in the modal.  

What is preventing the `firebaseUIContainer()` to show up?

Here's the modified code from the example:
```r
library(shiny)
library(firebase)

# define signin
signin <- modalDialog(
  title = "Login",
  firebaseUIContainer(),
  footer = NULL
)

ui <- fluidPage(
  useFirebase(),
  plotOutput("plot"),
  uiOutput("sign_out_button")
)

server <- function(input, output) {
  showModal(signin)
  
  f <- FirebaseUI$new(persistence = "local")$set_providers(
    email = TRUE,
    google = TRUE)$launch()
  

  observe({
    f$req_sign_in()
    removeModal()
  })
  
  output$plot <- renderPlot({
    f$req_sign_in()
    plot(cars)
  })
  
  ## Button for signing out
  output$sign_out_button <- shiny::renderUI({
    f$req_sign_in()
    actionButton("signout", "Sign out")
  })
  

  observeEvent(input$signout, {
    f$sign_out()
    showModal(signin)
  })
}

shinyApp(ui, server)
```

**Comment by JohnCoene** [comment]
You need to insert the firebase UI then launch, prior to every sign in.

```r
library(shiny)
library(firebase)

# define signin
signin <- modalDialog(
  title = "Login",
  firebaseUIContainer(),
  footer = NULL
)

ui <- fluidPage(
  useFirebase(),
  actionButton("logout", "Lougout"),
  plotOutput("plot"),
  uiOutput("sign_out_button")
)

server <- function(input, output) {
  f <- FirebaseUI$new(persistence = "local")$set_providers(
    email = TRUE,
    google = TRUE)

  observe({
    showModal(signin)
    f$launch()
  })

  observe({
    f$req_sign_in()
    removeModal()
  })
  
  output$plot <- renderPlot({
    f$req_sign_in()
    plot(cars)
  })
  
  ## Button for signing out
  output$sign_out_button <- shiny::renderUI({
    f$req_sign_in()
    actionButton("signout", "Sign out")
  })
  

  observeEvent(input$signout, {
    f$sign_out()
    showModal(signin)
    f$launch()
  })
}

shinyApp(ui, server)
```

It may be unclear in the documentation

**Comment by durraniu** [comment]
Thank you, this works!

**Comment by durraniu** [comment]
While this solution works, I noticed that if a previously signed-in user (persistent sign in ) switches to a different window/browser tab while the shiny app is loading, the modal shows up with sign in buttons (not desired). At the same time, the app contents also appear behind the modal. If the user stays in the shiny tab while the app is loading, the modal launches and removes almost immediately (desired result for a signed-in user). 

Any tips on how to stop the modal launching if a previously signed-in user switches to another window when the shiny app is loading @JohnCoene ?

**Comment by JohnCoene** [comment]
Did you try

```r
  observe({
    f$req_sign_out()
    showModal(signin)
    f$launch()
  })
```

**Comment by durraniu** [comment]
> Did you try
> 
> ```r
>   observe({
>     f$req_sign_out()
>     showModal(signin)
>     f$launch()
>   })
> ```

I just tried but got `Warning: Error in !: invalid argument type` with `f$req_sign_out()`. So, I installed the development version of firebase but got the same error. Then I tried the packer based installation but got an error:

```
> remotes::install_github("JohnCoene/firebase@packer")
Downloading GitHub repo JohnCoene/firebase@packer
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/JohnCoene/firebase/tarball/packer'
```

**Comment by JohnCoene** [comment]
It's not ideal but I think this should do it.

```r
library(shiny)
library(firebase)

# define signin
signin <- modalDialog(
  title = "Login",
  firebaseUIContainer(),
  footer = NULL
)

ui <- fluidPage(
  useFirebase(),
  actionButton("logout", "Lougout"),
  plotOutput("plot"),
  uiOutput("sign_out_button")
)

server <- function(input, output) {
  f <- FirebaseUI$new(persistence = "local")$set_providers(
    email = TRUE,
    google = TRUE)

  modal_shown <- reactiveVal(FALSE)
  observe({
    user <- f$get_signed_in()
    if(modal_shown())
      return()
    modal_shown(TRUE)
    showModal(signin)
    f$launch()
  })

  observe({
    f$req_sign_in()
    modal_shown(FALSE)
    removeModal()
  })
  
  output$plot <- renderPlot({
    f$req_sign_in()
    plot(cars)
  })
  
  ## Button for signing out
  output$sign_out_button <- shiny::renderUI({
    f$req_sign_in()
    actionButton("signout", "Sign out")
  })
  

  observeEvent(input$signout, {
    f$sign_out()
    showModal(signin)
    f$launch()
  })
}

shinyApp(ui, server)
```

**Comment by durraniu** [comment]
Thank you for your time in looking into this. I tried the suggested code. It now fails to remove the modal after sign in. In the following part:

```
observe({
    user <- f$get_signed_in()
    if(modal_shown())
      return()
    modal_shown(TRUE)
    showModal(signin)
    f$launch()
  })
```

I am not sure what `if(modal_shown()) return()` is for. 

I see `f$req_sign_out()` in the source code, is it not released yet?

**Comment by JohnCoene** [comment]
Ah I guess you must wrap `modal_shown()` in `isolate` since it's not meant to react, or even use standard R object instead.

This is so it does not flash twice, you can try without.
