### ISSUE TITLE
add text to firebaseUIContainer

### ISSUE THREAD

**Issue by HugoGit39** [JohnCoene/firebase#77]
Hi

I wonder if its possible to add additional info or text to `firebaseUIContainer`.

I would like to add 1 line of text. Is that possible or is this a feauture request than?

**Comment by JohnCoene** [comment]
That piece of UI comes from Google, you can try to inject text with JavaScript if you want.

What text and where do you want to add?

**Comment by HugoGit39** [comment]
It would be great to ad a short line of text as footer for example. The way i use the UI is to first register, and afterwards registration via Stripe. So would be great to have an informative text line that people nuderstand the steps. A small image for branding would be even more awsome :)

**Comment by JohnCoene** [comment]
But you can just wrap the UI in a div and add what you want below.

```
div(
  firebaseUIContainer(),
  p("my text")
)
```

**Comment by HugoGit39** [comment]
I trief that indeed...howeve rmy workflow is that after sign-in via the firebaseUIContainer(), on ther server side it checks if the user has a stripe plan or not which shows via uiOutpu()...if I just add text in the div() is remains visible:

```
tabItems(
        tabItem(
          tabName = "account",
          div(useFirebase(), br(),br(),
              firebaseUIContainer(),
              uiOutput('tab_account_ui')
          )
        )
```

**Comment by HugoGit39** [comment]
In the end I got it to work.

Still wonder if the width of the container can be edited?

**Comment by JohnCoene** [comment]
If you inspect the HTML you can find the classes so you can use CSS.

Normally the width is responsive so there should not be need to change that.
