### ISSUE TITLE
ERR_HTTP_RESPONSE_CODE_FAILURE

### ISSUE THREAD

**Issue by johnbde** [JohnCoene/firebase#8]
Thanks for this great package.

The following error messages appear in console when firebase package gets loaded.

```
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:5610/firebase/js/firebase-app.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:5610/firebase/js/firebase-auth.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:5610/firebase/js/firebase-analytics.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by JohnCoene** [comment]
Ah these are just warnings and do not break anything. The `.map` files are not required when running firebase in production, only to traceback errors when developing and debugging the firebase.js library itself. They can be safely ignored. 

If you encounter issues it's not because of this.

**Comment by johnbde** [comment]
Thanks for prompt response. Last question - Might sound stupid, do we really need all the 4-5 JS and CSS files for firebase which gets loaded with this package? I am trying my hard to optimize my app by removing unused CSS and JS.
