### ISSUE TITLE
Exclude firebase from shiny url bookmarking

### ISSUE THREAD

**Issue by udurraniAtPresage** [JohnCoene/firebase#81]
I am bookmarking my shiny app so that the data is restored after I refresh the app page. This app uses {firebase} authentication. If I use URL bookmarking, I see that firebase login is part of the URL. I want to exclude it. But what should I specify in `shiny::setBookmarkExclude` ?

**Comment by JohnCoene** [comment]
It might be `fireblaze_signed_in` and `fireblaze_signed_in_user`

**Comment by udurraniAtPresage** [comment]
Thank you.
